"""ingredients table

Revision ID: e37efd2680be
Revises: c2e8c0fab94f
Create Date: 2018-07-12 14:45:59.771963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37efd2680be'
down_revision = 'c2e8c0fab94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'ingredient_subcategory')
    op.drop_column('ingredient', 'storage_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('storage_location', sa.TEXT(), nullable=True))
    op.add_column('ingredient', sa.Column('ingredient_subcategory', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
